--
-- PostgreSQL database dump
--

\restrict r03arhKtjZBebgmBQ9U62iKpftK4ra8HeiuAzXT4fYKRzj1lBh2ZfHey6Bo1Kqc

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg12+2)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: articulos_articulo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articulos_articulo (
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    tags jsonb NOT NULL,
    "createdBy_id" uuid,
    "deletedBy_id" uuid,
    "updatedBy_id" uuid
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrusel_carrusel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carrusel_carrusel (
    id uuid NOT NULL,
    url character varying(200) NOT NULL,
    "isImage" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "createdBy_id" uuid,
    "isActive" boolean NOT NULL
);


--
-- Name: colonias_colonia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.colonias_colonia (
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    name character varying(255) NOT NULL,
    "createdBy_id" uuid,
    "deletedBy_id" uuid,
    "updatedBy_id" uuid
);


--
-- Name: decanatos_decanato; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decanatos_decanato (
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    name character varying(255) NOT NULL,
    "createdBy_id" uuid,
    "deletedBy_id" uuid,
    "updatedBy_id" uuid
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: documentos_documento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_documento (
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    title character varying(255) NOT NULL,
    document character varying(255) NOT NULL,
    type character varying(20) NOT NULL,
    tags jsonb NOT NULL,
    "createdBy_id" uuid,
    "deletedBy_id" uuid,
    "updatedBy_id" uuid
);


--
-- Name: noticias_noticia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.noticias_noticia (
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    title character varying(255) NOT NULL,
    picture character varying(255),
    content text NOT NULL,
    tags jsonb NOT NULL,
    "createdBy_id" uuid,
    "deletedBy_id" uuid,
    "updatedBy_id" uuid
);


--
-- Name: padres_padre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.padres_padre (
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    id uuid NOT NULL,
    "firstName" character varying(100) NOT NULL,
    "lastName" character varying(100) NOT NULL,
    "birthDate" date NOT NULL,
    picture character varying(255),
    "deletedBy_id" uuid,
    "updatedBy_id" uuid,
    email character varying(254),
    facebook character varying(200),
    instagram character varying(200),
    twitter character varying(200)
);


--
-- Name: parroquias_parroquia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parroquias_parroquia (
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    name character varying(255) NOT NULL,
    "openingDate" date NOT NULL,
    address text NOT NULL,
    "zipCode" character varying(10) NOT NULL,
    town character varying(100) NOT NULL,
    "coloniaId_id" uuid NOT NULL,
    "createdBy_id" uuid,
    "decanatoId_id" uuid NOT NULL,
    "deletedBy_id" uuid,
    "padreId_id" uuid NOT NULL,
    "updatedBy_id" uuid,
    picture character varying(255)
);


--
-- Name: usuarios_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    "isActive" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone,
    username character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(10) NOT NULL,
    is_staff boolean NOT NULL,
    "deletedBy_id" uuid,
    "updatedBy_id" uuid,
    is_active boolean NOT NULL
);


--
-- Name: usuarios_usuario_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_groups (
    id bigint NOT NULL,
    usuario_id uuid NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id uuid NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articulos_articulo articulos_articulo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articulos_articulo
    ADD CONSTRAINT articulos_articulo_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: carrusel_carrusel carrusel_carrusel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrusel_carrusel
    ADD CONSTRAINT carrusel_carrusel_pkey PRIMARY KEY (id);


--
-- Name: colonias_colonia colonias_colonia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colonias_colonia
    ADD CONSTRAINT colonias_colonia_pkey PRIMARY KEY (id);


--
-- Name: decanatos_decanato decanatos_decanato_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decanatos_decanato
    ADD CONSTRAINT decanatos_decanato_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: documentos_documento documentos_documento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_documento
    ADD CONSTRAINT documentos_documento_pkey PRIMARY KEY (id);


--
-- Name: noticias_noticia noticias_noticia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.noticias_noticia
    ADD CONSTRAINT noticias_noticia_pkey PRIMARY KEY (id);


--
-- Name: padres_padre padres_padre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.padres_padre
    ADD CONSTRAINT padres_padre_pkey PRIMARY KEY (id);


--
-- Name: parroquias_parroquia parroquias_parroquia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT parroquias_parroquia_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_email_key UNIQUE (email);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq UNIQUE (usuario_id, group_id);


--
-- Name: usuarios_usuario usuarios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_username_key UNIQUE (username);


--
-- Name: articulos_articulo_createdBy_id_76333383; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "articulos_articulo_createdBy_id_76333383" ON public.articulos_articulo USING btree ("createdBy_id");


--
-- Name: articulos_articulo_deletedBy_id_0ca7fb5b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "articulos_articulo_deletedBy_id_0ca7fb5b" ON public.articulos_articulo USING btree ("deletedBy_id");


--
-- Name: articulos_articulo_updatedBy_id_2378745f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "articulos_articulo_updatedBy_id_2378745f" ON public.articulos_articulo USING btree ("updatedBy_id");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: carrusel_carrusel_createdBy_id_7c0299b4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "carrusel_carrusel_createdBy_id_7c0299b4" ON public.carrusel_carrusel USING btree ("createdBy_id");


--
-- Name: colonias_colonia_createdBy_id_fdb5f9d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "colonias_colonia_createdBy_id_fdb5f9d1" ON public.colonias_colonia USING btree ("createdBy_id");


--
-- Name: colonias_colonia_deletedBy_id_1a2cfbb5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "colonias_colonia_deletedBy_id_1a2cfbb5" ON public.colonias_colonia USING btree ("deletedBy_id");


--
-- Name: colonias_colonia_updatedBy_id_1275c4ce; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "colonias_colonia_updatedBy_id_1275c4ce" ON public.colonias_colonia USING btree ("updatedBy_id");


--
-- Name: decanatos_decanato_createdBy_id_978ed3ec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "decanatos_decanato_createdBy_id_978ed3ec" ON public.decanatos_decanato USING btree ("createdBy_id");


--
-- Name: decanatos_decanato_deletedBy_id_081a6a2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "decanatos_decanato_deletedBy_id_081a6a2c" ON public.decanatos_decanato USING btree ("deletedBy_id");


--
-- Name: decanatos_decanato_updatedBy_id_253c7f36; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "decanatos_decanato_updatedBy_id_253c7f36" ON public.decanatos_decanato USING btree ("updatedBy_id");


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: documentos_documento_createdBy_id_55ffa2c6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "documentos_documento_createdBy_id_55ffa2c6" ON public.documentos_documento USING btree ("createdBy_id");


--
-- Name: documentos_documento_deletedBy_id_8d0d8772; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "documentos_documento_deletedBy_id_8d0d8772" ON public.documentos_documento USING btree ("deletedBy_id");


--
-- Name: documentos_documento_updatedBy_id_83e9e029; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "documentos_documento_updatedBy_id_83e9e029" ON public.documentos_documento USING btree ("updatedBy_id");


--
-- Name: noticias_noticia_createdBy_id_d055de9d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "noticias_noticia_createdBy_id_d055de9d" ON public.noticias_noticia USING btree ("createdBy_id");


--
-- Name: noticias_noticia_deletedBy_id_f85aa04f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "noticias_noticia_deletedBy_id_f85aa04f" ON public.noticias_noticia USING btree ("deletedBy_id");


--
-- Name: noticias_noticia_updatedBy_id_0aa687bd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "noticias_noticia_updatedBy_id_0aa687bd" ON public.noticias_noticia USING btree ("updatedBy_id");


--
-- Name: padres_padre_deletedBy_id_09365b89; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "padres_padre_deletedBy_id_09365b89" ON public.padres_padre USING btree ("deletedBy_id");


--
-- Name: padres_padre_updatedBy_id_66835c95; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "padres_padre_updatedBy_id_66835c95" ON public.padres_padre USING btree ("updatedBy_id");


--
-- Name: parroquias_parroquia_coloniaId_id_788533d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "parroquias_parroquia_coloniaId_id_788533d8" ON public.parroquias_parroquia USING btree ("coloniaId_id");


--
-- Name: parroquias_parroquia_createdBy_id_10d4cd4a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "parroquias_parroquia_createdBy_id_10d4cd4a" ON public.parroquias_parroquia USING btree ("createdBy_id");


--
-- Name: parroquias_parroquia_decanatoId_id_c3204cd1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "parroquias_parroquia_decanatoId_id_c3204cd1" ON public.parroquias_parroquia USING btree ("decanatoId_id");


--
-- Name: parroquias_parroquia_deletedBy_id_d8b711dd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "parroquias_parroquia_deletedBy_id_d8b711dd" ON public.parroquias_parroquia USING btree ("deletedBy_id");


--
-- Name: parroquias_parroquia_padreId_id_dd063430; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "parroquias_parroquia_padreId_id_dd063430" ON public.parroquias_parroquia USING btree ("padreId_id");


--
-- Name: parroquias_parroquia_updatedBy_id_a65afdc4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "parroquias_parroquia_updatedBy_id_a65afdc4" ON public.parroquias_parroquia USING btree ("updatedBy_id");


--
-- Name: usuarios_usuario_deletedBy_id_184ce499; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuarios_usuario_deletedBy_id_184ce499" ON public.usuarios_usuario USING btree ("deletedBy_id");


--
-- Name: usuarios_usuario_email_0a82e5f9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_email_0a82e5f9_like ON public.usuarios_usuario USING btree (email varchar_pattern_ops);


--
-- Name: usuarios_usuario_groups_group_id_e77f6dcf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_group_id_e77f6dcf ON public.usuarios_usuario_groups USING btree (group_id);


--
-- Name: usuarios_usuario_groups_usuario_id_7a34077f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_usuario_id_7a34077f ON public.usuarios_usuario_groups USING btree (usuario_id);


--
-- Name: usuarios_usuario_updatedBy_id_fc2ef36d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "usuarios_usuario_updatedBy_id_fc2ef36d" ON public.usuarios_usuario USING btree ("updatedBy_id");


--
-- Name: usuarios_usuario_user_permissions_permission_id_4e5c0f2f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_permission_id_4e5c0f2f ON public.usuarios_usuario_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuario_user_permissions_usuario_id_60aeea80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_usuario_id_60aeea80 ON public.usuarios_usuario_user_permissions USING btree (usuario_id);


--
-- Name: usuarios_usuario_username_be9def2b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_username_be9def2b_like ON public.usuarios_usuario USING btree (username varchar_pattern_ops);


--
-- Name: articulos_articulo articulos_articulo_createdBy_id_76333383_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articulos_articulo
    ADD CONSTRAINT "articulos_articulo_createdBy_id_76333383_fk_usuarios_usuario_id" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: articulos_articulo articulos_articulo_deletedBy_id_0ca7fb5b_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articulos_articulo
    ADD CONSTRAINT "articulos_articulo_deletedBy_id_0ca7fb5b_fk_usuarios_usuario_id" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: articulos_articulo articulos_articulo_updatedBy_id_2378745f_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articulos_articulo
    ADD CONSTRAINT "articulos_articulo_updatedBy_id_2378745f_fk_usuarios_usuario_id" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carrusel_carrusel carrusel_carrusel_createdBy_id_7c0299b4_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrusel_carrusel
    ADD CONSTRAINT "carrusel_carrusel_createdBy_id_7c0299b4_fk_usuarios_usuario_id" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: colonias_colonia colonias_colonia_createdBy_id_fdb5f9d1_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colonias_colonia
    ADD CONSTRAINT "colonias_colonia_createdBy_id_fdb5f9d1_fk_usuarios_usuario_id" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: colonias_colonia colonias_colonia_deletedBy_id_1a2cfbb5_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colonias_colonia
    ADD CONSTRAINT "colonias_colonia_deletedBy_id_1a2cfbb5_fk_usuarios_usuario_id" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: colonias_colonia colonias_colonia_updatedBy_id_1275c4ce_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.colonias_colonia
    ADD CONSTRAINT "colonias_colonia_updatedBy_id_1275c4ce_fk_usuarios_usuario_id" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: decanatos_decanato decanatos_decanato_createdBy_id_978ed3ec_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decanatos_decanato
    ADD CONSTRAINT "decanatos_decanato_createdBy_id_978ed3ec_fk_usuarios_usuario_id" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: decanatos_decanato decanatos_decanato_deletedBy_id_081a6a2c_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decanatos_decanato
    ADD CONSTRAINT "decanatos_decanato_deletedBy_id_081a6a2c_fk_usuarios_usuario_id" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: decanatos_decanato decanatos_decanato_updatedBy_id_253c7f36_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decanatos_decanato
    ADD CONSTRAINT "decanatos_decanato_updatedBy_id_253c7f36_fk_usuarios_usuario_id" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id FOREIGN KEY (user_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documentos_documento documentos_documento_createdBy_id_55ffa2c6_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_documento
    ADD CONSTRAINT "documentos_documento_createdBy_id_55ffa2c6_fk_usuarios_" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documentos_documento documentos_documento_deletedBy_id_8d0d8772_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_documento
    ADD CONSTRAINT "documentos_documento_deletedBy_id_8d0d8772_fk_usuarios_" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documentos_documento documentos_documento_updatedBy_id_83e9e029_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_documento
    ADD CONSTRAINT "documentos_documento_updatedBy_id_83e9e029_fk_usuarios_" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: noticias_noticia noticias_noticia_createdBy_id_d055de9d_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.noticias_noticia
    ADD CONSTRAINT "noticias_noticia_createdBy_id_d055de9d_fk_usuarios_usuario_id" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: noticias_noticia noticias_noticia_deletedBy_id_f85aa04f_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.noticias_noticia
    ADD CONSTRAINT "noticias_noticia_deletedBy_id_f85aa04f_fk_usuarios_usuario_id" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: noticias_noticia noticias_noticia_updatedBy_id_0aa687bd_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.noticias_noticia
    ADD CONSTRAINT "noticias_noticia_updatedBy_id_0aa687bd_fk_usuarios_usuario_id" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: padres_padre padres_padre_deletedBy_id_09365b89_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.padres_padre
    ADD CONSTRAINT "padres_padre_deletedBy_id_09365b89_fk_usuarios_usuario_id" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: padres_padre padres_padre_updatedBy_id_66835c95_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.padres_padre
    ADD CONSTRAINT "padres_padre_updatedBy_id_66835c95_fk_usuarios_usuario_id" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parroquias_parroquia parroquias_parroquia_coloniaId_id_788533d8_fk_colonias_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT "parroquias_parroquia_coloniaId_id_788533d8_fk_colonias_" FOREIGN KEY ("coloniaId_id") REFERENCES public.colonias_colonia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parroquias_parroquia parroquias_parroquia_createdBy_id_10d4cd4a_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT "parroquias_parroquia_createdBy_id_10d4cd4a_fk_usuarios_" FOREIGN KEY ("createdBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parroquias_parroquia parroquias_parroquia_decanatoId_id_c3204cd1_fk_decanatos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT "parroquias_parroquia_decanatoId_id_c3204cd1_fk_decanatos" FOREIGN KEY ("decanatoId_id") REFERENCES public.decanatos_decanato(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parroquias_parroquia parroquias_parroquia_deletedBy_id_d8b711dd_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT "parroquias_parroquia_deletedBy_id_d8b711dd_fk_usuarios_" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parroquias_parroquia parroquias_parroquia_padreId_id_dd063430_fk_padres_padre_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT "parroquias_parroquia_padreId_id_dd063430_fk_padres_padre_id" FOREIGN KEY ("padreId_id") REFERENCES public.padres_padre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parroquias_parroquia parroquias_parroquia_updatedBy_id_a65afdc4_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parroquias_parroquia
    ADD CONSTRAINT "parroquias_parroquia_updatedBy_id_a65afdc4_fk_usuarios_" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario usuarios_usuario_deletedBy_id_184ce499_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT "usuarios_usuario_deletedBy_id_184ce499_fk_usuarios_usuario_id" FOREIGN KEY ("deletedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario usuarios_usuario_updatedBy_id_fc2ef36d_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT "usuarios_usuario_updatedBy_id_fc2ef36d_fk_usuarios_usuario_id" FOREIGN KEY ("updatedBy_id") REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict r03arhKtjZBebgmBQ9U62iKpftK4ra8HeiuAzXT4fYKRzj1lBh2ZfHey6Bo1Kqc

